from __future__ import annotations

from collections import Counter
from pathlib import Path
import sys

sys.dont_write_bytecode = True

from kb_lib import (  # noqa: E402
    LEDGER_DIR,
    ROOT,
    access_cost,
    aliases,
    compact,
    load_datasets,
    read_jsonl,
    strongest_use,
    time_summary,
    used_by_count,
    atomic_write_text,
    workspace_lock,
)


STATUS_ORDER = {"ready": 0, "grounding": 1, "needs-review": 2, "candidate": 3, "deprecated": 4}


def write(path: Path, lines: list[str]) -> None:
    atomic_write_text(path, "\n".join(lines).rstrip() + "\n")


def build_index(records: list) -> None:
    active = [record for record in records if record.status != "deprecated"]
    active.sort(key=lambda item: (STATUS_ORDER.get(item.status, 99), -used_by_count(item), item.id))
    lines = [
        "# Dataset Index (Idea Router)",
        "",
        "> Generated by `scripts/build_views.py`. Do not edit by hand.",
        "> `ready` records may be recommended directly; describe the unresolved grounding gap for every `grounding` record.",
        "",
        "| slug | status | dataset | observation unit | coverage | access | strongest use | used_by |",
        "|---|---|---|---|---|---|---|---:|",
    ]
    for record in active:
        relative = record.path.relative_to(ROOT).as_posix()
        lines.append(
            "| "
            + " | ".join(
                [
                    f"[{record.id}]({relative})",
                    record.status,
                    compact(record.data.get("name"), 38),
                    compact(record.data.get("unit_of_observation"), 32),
                    compact(time_summary(record), 28),
                    compact(access_cost(record), 18),
                    compact(strongest_use(record), 48),
                    str(used_by_count(record)),
                ]
            )
            + f" | <!-- dataset:{record.id} -->"
        )

    deprecated = [record for record in records if record.status == "deprecated"]
    if deprecated:
        lines.extend(["", "## Deprecated redirects", ""])
        for record in sorted(deprecated, key=lambda item: item.id):
            targets = ", ".join(record.data.get("superseded_by", []))
            relative = record.path.relative_to(ROOT).as_posix()
            lines.append(f"- [{record.id}]({relative}) -> {targets}")
    write(ROOT / "DATASET_INDEX.md", lines)


def build_aliases(records: list) -> None:
    active = [record for record in records if record.status != "deprecated"]
    active.sort(key=lambda item: item.id)
    lines = [
        "# Dataset Aliases (alias -> canonical slug)",
        "",
        "> Generated by `scripts/build_views.py` from each record's `aka` values. Do not edit by hand. Candidates are excluded.",
        "",
        "| aliases and common names | canonical slug | status |",
        "|---|---|---|",
    ]
    for record in active:
        names = "; ".join(aliases(record)) or "needs completion"
        lines.append(f"| {compact(names, 110)} | `{record.id}` | {record.status} |")
    write(LEDGER_DIR / "aliases.md", lines)


def build_snapshot(records: list) -> None:
    status_counts = Counter(record.status for record in records)
    active = [record for record in records if record.status != "deprecated"]
    total_uses = sum(used_by_count(record) for record in active)
    candidates, _ = read_jsonl(LEDGER_DIR / "dataset_candidates.jsonl")
    pending, _ = read_jsonl(LEDGER_DIR / "pending_tasks.jsonl")
    failed, _ = read_jsonl(LEDGER_DIR / "failed_tasks.jsonl")
    health_path = LEDGER_DIR / "health.json"
    health_status = "not generated"
    health_errors = "?"
    health_warnings = "?"
    if health_path.exists():
        import json

        health = json.loads(health_path.read_text(encoding="utf-8"))
        health_status = health.get("status", "unknown")
        health_errors = len(health.get("errors", []))
        health_warnings = len(health.get("warnings", []))

    top = sorted(active, key=lambda item: (-used_by_count(item), item.id))[:8]
    lines = [
        "# Progress and Quality Snapshot",
        "",
        "> Generated by `scripts/build_views.py`. Do not edit by hand.",
        "",
        "## Current health",
        "",
        f"- Active canonical records: {len(active)} (ready {status_counts['ready']} / grounding {status_counts['grounding']} / needs-review {status_counts['needs-review']})",
        f"- Deprecated redirects: {status_counts['deprecated']}; candidates: {len(candidates)}",
        f"- Recorded paper uses: {total_uses} (a traceability count, not an overall quality score)",
        f"- Tasks: pending/claimed {len(pending)}; failed/blocked {len(failed)}",
        f"- Latest health check: {health_status}; errors {health_errors}; warnings {health_warnings}",
        "",
        "## Frequently used records",
        "",
        "| slug | status | used_by |",
        "|---|---|---:|",
    ]
    for record in top:
        lines.append(f"| {record.id} | {record.status} | {used_by_count(record)} |")
    lines.extend(["", "## Candidate gaps", ""])
    for row in candidates:
        lines.append(f"- `{row.get('id')}` {row.get('name')}: {row.get('next_action')}")
    lines.extend(
        [
            "",
            "## Next-run decision",
            "",
            "Read `ledgers/health.json` first. Resolve errors before collecting. Otherwise improve acquisition routes and comparison rules for `grounding` records before expanding the candidate pool.",
        ]
    )
    write(LEDGER_DIR / "progress.md", lines)


def main() -> int:
    with workspace_lock("derived-views"):
        records, failures = load_datasets()
        if failures:
            for path, error in failures:
                print(f"ERROR: {path.name}: {error}")
            return 1
        build_index(records)
        build_aliases(records)
        build_snapshot(records)
    print(f"generated views for {len(records)} dataset records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
